
services:
  easyshop_mongodb:
    container_name: easyshop_mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - easyshop_network
    volumes:
      - easyshop_db:/data/db
  easyshopfrontend:
    container_name: easyshop_frontend
    image: siddhantkudal/easyshop:latest
    ports:
      - "3000:3000"
    environment:
       MONGODB_URI: mongodb://easyshop_mongodb:27017/easyshop
      #  NEXTAUTH_URL: http://easyshopfrontend:3000
      #  NEXT_PUBLIC_API_URL: http://easyshopfrontend:3000/api

       PRODUCTION_NEXTAUTH_URL: http://localhost
       PRODUCTION_NEXT_PUBLIC_API_URL: http://localhost/api
       NEXTAUTH_SECRET: r12jcpiPdWUZGA1xmRCjTDw9gIoltkrV/L/1sGQXGvM=
       JWT_SECRET: 36b9bbc7dbaed10e8ef2354dc9a323823df3e05cf2a7cd8f8b2ba2ace519795e
    networks:
      - easyshop_network
    depends_on:
      - easyshop_mongodb
  mongodbmigration:
    container_name: mongomigration
    image: siddhantkudal/docker_migrate:1
    networks:
      - easyshop_network
    depends_on:
      - easyshop_mongodb
networks:
  easyshop_network:
    driver: bridge
volumes:
  easyshop_db:
    name: easyshop_db
  
