kind: ConfigMap
apiVersion: v1
metadata:
  name: easyshopconfig
  namespace: easyshop
data:
  mongodburi: mongodb://easyshopmongodb:27017/easyshop
  production_url: http://localhost
  production_apiurl: http://localhost/api


  