apiVersion: batch/v1
kind: Job
metadata:
  name: dbmigrate
<<<<<<< HEAD
  namespace: easyshop
=======
>>>>>>> 0052cdefb19de7b6dfacb368b0eff2bab7083297
spec:
  template:
    spec:
      containers:
        - name: dbmigrate
          image: siddhantkudal/docker_migrate:1
          env:
          - name: MONGODB_URI
            value: mongodb://easyshopmongodb.easyshop.svc.cluster.local:27017/easyshop
      restartPolicy: Never
  backoffLimit: 4
