kind: Secret
apiVersion: v1
metadata:
  name: easyshopsecret
  namespace: easyshop
type: opaque
data:
  nextauth: r12jcpiPdWUZGA1xmRCjTDw9gIoltkrV/L/1sGQXGvM=
  jwttoken: 36b9bbc7dbaed10e8ef2354dc9a323823df3e05cf2a7cd8f8b2ba2ace519795e


